#### Numpy

In [1]:
import numpy
import numpy as np
from numpy import*

In [2]:
list=[5,6,7]

In [4]:
type(list)

list

In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [13]:
arr=np.array(list)

In [7]:
arr

array([5, 6, 7])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim

1

In [10]:
arr.shape

(3,)

In [16]:
list1=[1,2,3]
a=np.array(list,ndmin=2)

In [17]:
a

array([[5, 6, 7]])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.ndim

2

In [20]:
arr

array([5, 6, 7])

In [21]:
arr[1]

6

In [26]:
b=arr.astype(float)

In [27]:
b

array([5., 6., 7.])

In [24]:
arr.size

3

In [28]:
b.dtype

dtype('float64')

In [33]:
c=['a','b','c']
d=np.array(c,ndmin=2)

In [34]:
d

array([['a', 'b', 'c']], dtype='<U1')

In [35]:
c.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [36]:
arr.itemsize

4

In [37]:
len(arr)

3

In [38]:
arr2=np.array([3,4,5,6,7,8])

In [39]:
arr2

array([3, 4, 5, 6, 7, 8])

In [40]:
arr2[2:5]

array([5, 6, 7])

In [41]:
arr2[1]=50

In [42]:
arr2

array([ 3, 50,  5,  6,  7,  8])

In [43]:
list=[[1,2,3],[1,3,4],[8,9,10]]

In [44]:
list1=np.array(list)

In [45]:
list1

array([[ 1,  2,  3],
       [ 1,  3,  4],
       [ 8,  9, 10]])

In [46]:
list1.ndim

2

In [47]:
list1.shape

(3, 3)

In [79]:
a=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [80]:
type(a)

list

In [81]:
b=np.array(a)

In [82]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
b[0]

array([1, 2, 3, 4, 5])

In [54]:
b[3]

array([16, 17, 18, 19, 20])

In [57]:
#b[no of rows you want, no of colm you want]
b[0:4,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [59]:
b[0:4,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [61]:
for i in range(4):
    print(b[i][3])

4
9
14
19


In [62]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [63]:
b[3,2:5]

array([18, 19, 20])

In [64]:
b[1,4]

10

In [87]:
#diagonal
b.diagonal(offset=1)

array([ 2,  8, 14, 20])

In [75]:
c

array([ 2,  8, 14, 20])

In [71]:
c[2]

13

### Numpy Functions

In [ ]:
1.zeros
2. ones
3. eye
4. random.rand
5.random.randint
6. linspace
7. arange
8. concatenate
9. flatten
10. ravel
11 transpose

In [90]:
#zero
zero = np.zeros(6,dtype=int)

In [91]:
zero

array([0, 0, 0, 0, 0, 0])

In [92]:
zero.ndim

1

In [95]:
zero=np.zeros((4,4),dtype=int)

In [96]:
zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
#ones
one=np.ones(6)

In [98]:
one

array([1., 1., 1., 1., 1., 1.])

In [101]:
one=np.ones((5,4),dtype=int)

In [102]:
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [112]:
#identity matrix
a=np.eye(4,4,dtype=int)

In [116]:
np.repeat(a,2,axis=0)

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [108]:
a.diagonal()

array([1, 1, 1, 1])

In [109]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [111]:
a=np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [120]:
#arange
array = np.arange(10,20)

In [121]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [125]:
array.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [129]:
ar1=np.arange(1,20)
ar2=ar1[ar1%2==0]

In [130]:
ar2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [133]:
ar2.reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [134]:
ar1=np.arange(1,20)
ar2=ar1[ar1%2==1]

In [135]:
ar2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [136]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [138]:
a.reshape(3,2)

ValueError: cannot reshape array of size 4 into shape (3,2)

In [141]:
np.resize(a,(5,2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2]])

In [12]:
#random.rand
a=np.random.rand(5)

In [13]:
a.ndim

1

In [14]:
np.random.rand(3,3)

array([[0.39396141, 0.4464603 , 0.92410361],
       [0.90748667, 0.47278253, 0.7339242 ],
       [0.14900713, 0.10143193, 0.6372984 ]])

In [33]:
b=np.random.randint(1,10,20).reshape(4,5)

In [34]:
b.ndim

2

In [35]:
b

array([[2, 5, 1, 1, 9],
       [3, 7, 5, 2, 5],
       [5, 3, 5, 5, 3],
       [4, 7, 6, 6, 9]])

In [41]:
b1=np.random.randn(10)

In [42]:
b1

array([-0.13182679, -1.50113189, -1.30833081, -0.11969101,  1.19286585,
        0.75670314,  0.08972824, -1.00689321,  1.81346277,  0.64440011])

In [43]:
x=np.random.normal(size=(2,3))

In [44]:
x

array([[-1.50692959, -1.29219755,  0.56421569],
       [-0.48147053,  0.83815421,  2.24588402]])

In [45]:
x=np.random.uniform(size=(2,3))

In [46]:
x

array([[0.94003968, 0.38281935, 0.73128978],
       [0.97549651, 0.59554869, 0.84691322]])

In [51]:
#linspace
np.linspace(0,10,2)

array([ 0., 10.])

In [52]:
#ravel
b

array([[2, 5, 1, 1, 9],
       [3, 7, 5, 2, 5],
       [5, 3, 5, 5, 3],
       [4, 7, 6, 6, 9]])

In [53]:
a=b.ravel()

In [54]:
a

array([2, 5, 1, 1, 9, 3, 7, 5, 2, 5, 5, 3, 5, 5, 3, 4, 7, 6, 6, 9])

In [67]:
#flatten
c=b.flatten()

In [56]:
c

array([2, 5, 1, 1, 9, 3, 7, 5, 2, 5, 5, 3, 5, 5, 3, 4, 7, 6, 6, 9])

In [57]:
np.__version__

'1.19.5'

In [58]:
#ravel array
a

array([2, 5, 1, 1, 9, 3, 7, 5, 2, 5, 5, 3, 5, 5, 3, 4, 7, 6, 6, 9])

In [59]:
#flatten array
c

array([2, 5, 1, 1, 9, 3, 7, 5, 2, 5, 5, 3, 5, 5, 3, 4, 7, 6, 6, 9])

In [60]:
a[5]= 90

In [61]:
a

array([ 2,  5,  1,  1,  9, 90,  7,  5,  2,  5,  5,  3,  5,  5,  3,  4,  7,
        6,  6,  9])

In [62]:
b

array([[ 2,  5,  1,  1,  9],
       [90,  7,  5,  2,  5],
       [ 5,  3,  5,  5,  3],
       [ 4,  7,  6,  6,  9]])

In [63]:
c[5]= 50

In [64]:
c

array([ 2,  5,  1,  1,  9, 50,  7,  5,  2,  5,  5,  3,  5,  5,  3,  4,  7,
        6,  6,  9])

In [65]:
b

array([[ 2,  5,  1,  1,  9],
       [90,  7,  5,  2,  5],
       [ 5,  3,  5,  5,  3],
       [ 4,  7,  6,  6,  9]])

In [87]:
#concatenate
a=np.arange(9).reshape(3,3)

In [88]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
b=np.arange(1,10).reshape(3,3)

In [90]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
c=np.concatenate((a,b),axis=1)

In [92]:
c

array([[0, 1, 2, 1, 2, 3],
       [3, 4, 5, 4, 5, 6],
       [6, 7, 8, 7, 8, 9]])

a="Hello"
b="Welcome"
c=a+b

In [93]:
c

array([[0, 1, 2, 1, 2, 3],
       [3, 4, 5, 4, 5, 6],
       [6, 7, 8, 7, 8, 9]])

In [94]:
a=c.transpose()

In [95]:
a

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### operations on an array

In [96]:
arr = np.arange(1,20)

In [97]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [98]:
arr.sum()

190

In [99]:
b=np.cumsum(arr)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [ ]:
b

In [100]:
arr.min()

1

In [101]:
arr.max()

19

In [102]:
arr.argmin()

0

In [103]:
arr.argmax()

18

In [104]:
arr.mean()

10.0

In [105]:
np.median(arr)

10.0

In [106]:
np.var(arr)

30.0

In [107]:
np.std(arr)

5.477225575051661

In [112]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [113]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [114]:
a.sum()

210

In [115]:
a.max()

20

In [117]:
a.argmax()

19

In [118]:
a.argmin()

0

In [121]:
np.amin(a,axis=1)

array([ 1,  6, 11, 16])

In [122]:
np.amin(a,axis=0)

array([1, 2, 3, 4, 5])

In [124]:
a=np.arange(0,10)

In [125]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
c=np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [128]:
c=a*a

In [129]:
c

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
c.ndim

1

In [131]:
c.shape

(10,)

In [132]:
c.reshape(5,2)

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [135]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [137]:
np.exp(c)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [138]:
c>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [148]:
#missing values in array
a=np.array([10,np.nan,20,30,60,np.nan,90,np.inf])

In [149]:
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [150]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [151]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [153]:
a[np.isnan(a)]=100
#a[1,5]=100

In [154]:
a

array([ 10., 100.,  20.,  30.,  60., 100.,  90.,  inf])

In [155]:
np.isnan(a).any()

False

In [156]:
a

array([ 10., 100.,  20.,  30.,  60., 100.,  90.,  inf])