Dataset link: tinyurl.com/data-preprocess

In [105]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [106]:
import requests
import io
url="https://github.com/rammohanbethi/Book-Recommendation-System/blob/master/BX-Books.csv"
s=requests.get(url).content
data=pd.read_csv(io.StringIO(s.decode('utf-8')))

ParserError: Error tokenizing data. C error: Expected 1 fields in line 89, saw 2


In [ ]:
#importing dataset or reading the dataset
dataset=pd.read_csv(r'C:\Users\smartbridge\Desktop\Internship\Data.csv')

In [ ]:
dataset

In [107]:
type(dataset)

pandas.core.frame.DataFrame

In [108]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     int64  
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     int64  
dtypes: float64(2), int64(2)
memory usage: 448.0 bytes


In [109]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

In [110]:
dataset.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [111]:
dataset[dataset['Age'].isnull()].index.tolist()

[]

In [112]:
dataset[dataset['Salary'].isnull()].index.tolist()

[]

In [113]:
dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)

In [114]:
dataset['Salary'].fillna(dataset['Salary'].mean(),inplace=True)

In [115]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

In [116]:
dataset

Country   Age        Salary  Purchased
0        0  44.0  72000.000000          0
1        2  27.0  48000.000000          1
2        1  30.0  54000.000000          0
3        2  38.0  61000.000000          0
4        1  40.0  63777.777778          1
5        0  35.0  58000.000000          1
6        2  39.0  52000.000000          0
7        0  48.0  79000.000000          1
8        1  50.0  83000.000000          0
9        0  37.0  67000.000000          1

In [117]:
dataset['Age']=dataset['Age'].round()

In [118]:
dataset

Country   Age        Salary  Purchased
0        0  44.0  72000.000000          0
1        2  27.0  48000.000000          1
2        1  30.0  54000.000000          0
3        2  38.0  61000.000000          0
4        1  40.0  63777.777778          1
5        0  35.0  58000.000000          1
6        2  39.0  52000.000000          0
7        0  48.0  79000.000000          1
8        1  50.0  83000.000000          0
9        0  37.0  67000.000000          1

In [119]:
dataset['Country'].unique()

array([0, 2, 1], dtype=int64)

In [120]:
#france - 0
#Germany-1
#spain -2

#no-0
#yes-1

In [121]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Country']=le.fit_transform(dataset['Country'])

In [122]:
dataset['Purchased']=le.fit_transform(dataset['Purchased'])

In [123]:
dataset

Country   Age        Salary  Purchased
0        0  44.0  72000.000000          0
1        2  27.0  48000.000000          1
2        1  30.0  54000.000000          0
3        2  38.0  61000.000000          0
4        1  40.0  63777.777778          1
5        0  35.0  58000.000000          1
6        2  39.0  52000.000000          0
7        0  48.0  79000.000000          1
8        1  50.0  83000.000000          0
9        0  37.0  67000.000000          1

In [124]:
#y=mx+c, no-0
#y=0.1*1+4=

0,1,2, 0>1,france>germany 1>2 germany>spain - 1,0,0

SyntaxError: invalid syntax (<ipython-input-124-30ff17e15526>, line 4)

In [125]:
#independent variables
x = dataset.iloc[:,0:3].values

In [126]:
x

array([[0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [2.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [2.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [2.00000000e+00, 3.90000000e+01, 5.20000000e+04],
       [0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [127]:
x.ndim

2

In [128]:
x.shape

(10, 3)

In [129]:
#dependent variable
y=dataset.iloc[:,-1:].values

In [130]:
y

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]], dtype=int64)

In [131]:
y.ndim

2

In [132]:
y.shape

(10, 1)

In [133]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder()

In [134]:
z=oh.fit_transform(x[:,0:1]).toarray()
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [135]:
dataset  #france -0 , #spain -2  #germany -1
train_test_splittrain_test_splittrain_test_splittrain_test_splittrain_test_splittrain_test_split
  #france Germany Spain california
0-    1     0       0     0
1-    0     0       1     0
2-    0     1       0     0
3-    0     0       0     1

SyntaxError: invalid syntax (<ipython-input-135-cb6fb8e0fff6>, line 4)

In [136]:
x=np.delete(x,0,axis=1)

In [137]:
x.shape

(10, 2)

In [138]:
z,x=1,0,0,age,salary

NameError: name 'age' is not defined

In [139]:
a=np.concatenate((x,z),axis=1)

In [140]:
x.shape

(10, 5)

In [147]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

#100 rows - 70% -30% -80/20

In [148]:
x_train.shape

(7, 5)

In [149]:
x_test.shape

(3, 5)

In [150]:
y_train.shape

(7, 1)

In [151]:
y_test.shape

(3, 1)