In [23]:
import numpy as np
import pandas as  pd
pd.options.display.float_format = '{:.2f}'.format

In [24]:
dataset = pd.read_csv(r"fish.csv")

In [25]:
dataset.head(5)

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream  242.00    23.20    25.40    30.00   11.52   4.02
1   Bream  290.00    24.00    26.30    31.20   12.48   4.31
2   Bream  340.00    23.90    26.50    31.10   12.38   4.70
3   Bream  363.00    26.30    29.00    33.50   12.73   4.46
4   Bream  430.00    26.50    29.00    34.00   12.44   5.13

In [26]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [27]:
dataset.head()

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream  242.00    23.20    25.40    30.00   11.52   4.02
1   Bream  290.00    24.00    26.30    31.20   12.48   4.31
2   Bream  340.00    23.90    26.50    31.10   12.38   4.70
3   Bream  363.00    26.30    29.00    33.50   12.73   4.46
4   Bream  430.00    26.50    29.00    34.00   12.44   5.13

In [28]:
dataset.head(5)

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream  242.00    23.20    25.40    30.00   11.52   4.02
1   Bream  290.00    24.00    26.30    31.20   12.48   4.31
2   Bream  340.00    23.90    26.50    31.10   12.38   4.70
3   Bream  363.00    26.30    29.00    33.50   12.73   4.46
4   Bream  430.00    26.50    29.00    34.00   12.44   5.13

In [29]:
dataset["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [30]:
dataset.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream  242.00    23.20    25.40    30.00   11.52   4.02

In [31]:
# 0 - Bream , 1 = Parkki 2 = perch 3 = pike 4 = Roach 5 = Smelt 6 = Whitefish

In [32]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Species']=le.fit_transform(dataset['Species'])

In [33]:
dataset.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0        0  242.00    23.20    25.40    30.00   11.52   4.02

In [34]:
x = dataset.iloc[:,1:7].values
y = dataset.iloc[:,0:1].values

In [35]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder = "passthrough")
y = ct.fit_transform(y)

In [36]:
y = y.toarray()

In [37]:
type(y)

numpy.ndarray

In [38]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [39]:
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [40]:
y.shape

(159, 7)

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 1)

In [42]:
x_train.shape

(111, 6)

In [43]:
y_train.shape

(111, 7)

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


In [46]:
categorical = Sequential()

In [47]:
categorical.add(Dense(units = 6 , kernel_initializer = "random_uniform",activation ="relu"))

In [48]:
categorical.add(Dropout(0.2))

In [49]:
categorical.add(Dense(units = 12 , kernel_initializer = "random_uniform",activation ="relu"))

In [50]:
categorical.add(Dropout(0.2))

In [51]:
categorical.add(Dense(units = 12 , kernel_initializer = "random_uniform",activation ="relu"))

In [52]:
categorical.add(Dropout(0.2))

In [53]:
categorical.add(Dense(units = 12 , kernel_initializer = "random_uniform",activation ="relu"))

In [54]:
categorical.add(Dense(units = 7 , kernel_initializer = "random_uniform",activation ="softmax"))

In [55]:
categorical.compile(optimizer = "rmsprop",loss="categorical_crossentropy" ,metrics = ["accuracy"])

In [56]:
history = categorical.fit(x_train,y_train, batch_size =128,epochs = 1000, validation_data = (x_test,y_test))

Epoch 1/1000
1/1 [==============================] - 3s 3s/step - loss: 1.9459 - accuracy: 0.1532 - val_loss: 1.9436 - val_accuracy: 0.2083
Epoch 2/1000
1/1 [==============================] - 0s 71ms/step - loss: 1.9441 - accuracy: 0.2252 - val_loss: 1.9419 - val_accuracy: 0.2083
Epoch 3/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.9428 - accuracy: 0.2252 - val_loss: 1.9404 - val_accuracy: 0.2083
Epoch 4/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.9417 - accuracy: 0.2252 - val_loss: 1.9391 - val_accuracy: 0.2083
Epoch 5/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.9406 - accuracy: 0.2252 - val_loss: 1.9378 - val_accuracy: 0.2083
Epoch 6/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.9397 - accuracy: 0.2252 - val_loss: 1.9366 - val_accuracy: 0.2083
Epoch 7/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.9387 - accuracy: 0.2252 - val_loss: 1.9354 - val_accuracy: 0.2083
Epoch 8/1000
1/

Epoch 59/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.8681 - accuracy: 0.2252 - val_loss: 1.8453 - val_accuracy: 0.2083
Epoch 60/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.8628 - accuracy: 0.2252 - val_loss: 1.8419 - val_accuracy: 0.2083
Epoch 61/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.8634 - accuracy: 0.2252 - val_loss: 1.8387 - val_accuracy: 0.2083
Epoch 62/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.8596 - accuracy: 0.2252 - val_loss: 1.8353 - val_accuracy: 0.2083
Epoch 63/1000
1/1 [==============================] - 0s 62ms/step - loss: 1.8581 - accuracy: 0.2252 - val_loss: 1.8318 - val_accuracy: 0.2083
Epoch 64/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.8550 - accuracy: 0.2252 - val_loss: 1.8284 - val_accuracy: 0.2083
Epoch 65/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.8543 - accuracy: 0.2252 - val_loss: 1.8249 - val_accuracy: 0.2083
Epoch 

1/1 [==============================] - 0s 64ms/step - loss: 1.7031 - accuracy: 0.3243 - val_loss: 1.6653 - val_accuracy: 0.4167
Epoch 117/1000
1/1 [==============================] - 0s 57ms/step - loss: 1.6832 - accuracy: 0.3243 - val_loss: 1.6643 - val_accuracy: 0.4167
Epoch 118/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6951 - accuracy: 0.3243 - val_loss: 1.6634 - val_accuracy: 0.4167
Epoch 119/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6922 - accuracy: 0.3243 - val_loss: 1.6627 - val_accuracy: 0.4167
Epoch 120/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6953 - accuracy: 0.3243 - val_loss: 1.6619 - val_accuracy: 0.4167
Epoch 121/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6706 - accuracy: 0.3243 - val_loss: 1.6613 - val_accuracy: 0.4167
Epoch 122/1000
1/1 [==============================] - 0s 63ms/step - loss: 1.6929 - accuracy: 0.3243 - val_loss: 1.6608 - val_accuracy: 0.4167
Epoch 123/1000

1/1 [==============================] - 0s 56ms/step - loss: 1.5959 - accuracy: 0.3694 - val_loss: 1.6558 - val_accuracy: 0.5417
Epoch 174/1000
1/1 [==============================] - 0s 54ms/step - loss: 1.6013 - accuracy: 0.3604 - val_loss: 1.6558 - val_accuracy: 0.5417
Epoch 175/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6274 - accuracy: 0.3874 - val_loss: 1.6547 - val_accuracy: 0.5417
Epoch 176/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.6178 - accuracy: 0.3423 - val_loss: 1.6540 - val_accuracy: 0.5417
Epoch 177/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6127 - accuracy: 0.3694 - val_loss: 1.6533 - val_accuracy: 0.5417
Epoch 178/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6239 - accuracy: 0.4054 - val_loss: 1.6524 - val_accuracy: 0.5417
Epoch 179/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.6195 - accuracy: 0.3423 - val_loss: 1.6520 - val_accuracy: 0.5417
Epoch 180/1000

1/1 [==============================] - 0s 56ms/step - loss: 1.5715 - accuracy: 0.3153 - val_loss: 1.6361 - val_accuracy: 0.5417
Epoch 231/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.5555 - accuracy: 0.3604 - val_loss: 1.6359 - val_accuracy: 0.5417
Epoch 232/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.5678 - accuracy: 0.3964 - val_loss: 1.6352 - val_accuracy: 0.5417
Epoch 233/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.5545 - accuracy: 0.3604 - val_loss: 1.6347 - val_accuracy: 0.5417
Epoch 234/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.5586 - accuracy: 0.3784 - val_loss: 1.6342 - val_accuracy: 0.5417
Epoch 235/1000
1/1 [==============================] - 0s 54ms/step - loss: 1.5479 - accuracy: 0.3604 - val_loss: 1.6362 - val_accuracy: 0.5417
Epoch 236/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.5757 - accuracy: 0.3784 - val_loss: 1.6360 - val_accuracy: 0.5417
Epoch 237/1000

1/1 [==============================] - 0s 56ms/step - loss: 1.5193 - accuracy: 0.3333 - val_loss: 1.6164 - val_accuracy: 0.5417
Epoch 288/1000
1/1 [==============================] - 0s 59ms/step - loss: 1.5344 - accuracy: 0.4054 - val_loss: 1.6159 - val_accuracy: 0.5417
Epoch 289/1000
1/1 [==============================] - 0s 51ms/step - loss: 1.5202 - accuracy: 0.3333 - val_loss: 1.6165 - val_accuracy: 0.5417
Epoch 290/1000
1/1 [==============================] - 0s 57ms/step - loss: 1.5259 - accuracy: 0.3514 - val_loss: 1.6168 - val_accuracy: 0.5417
Epoch 291/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.5199 - accuracy: 0.3604 - val_loss: 1.6192 - val_accuracy: 0.5417
Epoch 292/1000
1/1 [==============================] - 0s 53ms/step - loss: 1.5090 - accuracy: 0.3694 - val_loss: 1.6206 - val_accuracy: 0.5417
Epoch 293/1000
1/1 [==============================] - 0s 52ms/step - loss: 1.5404 - accuracy: 0.3694 - val_loss: 1.6163 - val_accuracy: 0.5417
Epoch 294/1000

1/1 [==============================] - 0s 60ms/step - loss: 1.5196 - accuracy: 0.3964 - val_loss: 1.5841 - val_accuracy: 0.5417
Epoch 345/1000
1/1 [==============================] - 0s 60ms/step - loss: 1.4775 - accuracy: 0.3694 - val_loss: 1.5843 - val_accuracy: 0.5417
Epoch 346/1000
1/1 [==============================] - 0s 53ms/step - loss: 1.5039 - accuracy: 0.3784 - val_loss: 1.5839 - val_accuracy: 0.5417
Epoch 347/1000
1/1 [==============================] - 0s 62ms/step - loss: 1.4783 - accuracy: 0.3874 - val_loss: 1.5836 - val_accuracy: 0.5417
Epoch 348/1000
1/1 [==============================] - 0s 58ms/step - loss: 1.4821 - accuracy: 0.3874 - val_loss: 1.5816 - val_accuracy: 0.5417
Epoch 349/1000
1/1 [==============================] - 0s 59ms/step - loss: 1.4652 - accuracy: 0.4054 - val_loss: 1.5801 - val_accuracy: 0.5417
Epoch 350/1000
1/1 [==============================] - 0s 67ms/step - loss: 1.4751 - accuracy: 0.3874 - val_loss: 1.5811 - val_accuracy: 0.5417
Epoch 351/1000

1/1 [==============================] - 0s 50ms/step - loss: 1.4553 - accuracy: 0.4414 - val_loss: 1.5358 - val_accuracy: 0.5625
Epoch 402/1000
1/1 [==============================] - 0s 53ms/step - loss: 1.4359 - accuracy: 0.4324 - val_loss: 1.5364 - val_accuracy: 0.5625
Epoch 403/1000
1/1 [==============================] - 0s 58ms/step - loss: 1.4490 - accuracy: 0.4685 - val_loss: 1.5335 - val_accuracy: 0.5625
Epoch 404/1000
1/1 [==============================] - 0s 53ms/step - loss: 1.4661 - accuracy: 0.4144 - val_loss: 1.5310 - val_accuracy: 0.5625
Epoch 405/1000
1/1 [==============================] - 0s 60ms/step - loss: 1.4590 - accuracy: 0.4324 - val_loss: 1.5296 - val_accuracy: 0.5625
Epoch 406/1000
1/1 [==============================] - 0s 53ms/step - loss: 1.4243 - accuracy: 0.4505 - val_loss: 1.5270 - val_accuracy: 0.5625
Epoch 407/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.4470 - accuracy: 0.4414 - val_loss: 1.5254 - val_accuracy: 0.5625
Epoch 408/1000

1/1 [==============================] - 0s 57ms/step - loss: 1.3739 - accuracy: 0.4414 - val_loss: 1.4747 - val_accuracy: 0.5833
Epoch 459/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.3678 - accuracy: 0.5405 - val_loss: 1.4720 - val_accuracy: 0.5833
Epoch 460/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.3794 - accuracy: 0.4595 - val_loss: 1.4704 - val_accuracy: 0.5833
Epoch 461/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.3596 - accuracy: 0.4955 - val_loss: 1.4685 - val_accuracy: 0.5833
Epoch 462/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.3155 - accuracy: 0.5495 - val_loss: 1.4656 - val_accuracy: 0.5833
Epoch 463/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.3932 - accuracy: 0.4595 - val_loss: 1.4699 - val_accuracy: 0.6042
Epoch 464/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.3821 - accuracy: 0.4775 - val_loss: 1.4682 - val_accuracy: 0.5833
Epoch 465/1000

1/1 [==============================] - 0s 56ms/step - loss: 1.3150 - accuracy: 0.4955 - val_loss: 1.4106 - val_accuracy: 0.6250
Epoch 516/1000
1/1 [==============================] - 0s 72ms/step - loss: 1.2972 - accuracy: 0.5135 - val_loss: 1.4063 - val_accuracy: 0.6250
Epoch 517/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.3075 - accuracy: 0.5135 - val_loss: 1.4020 - val_accuracy: 0.6250
Epoch 518/1000
1/1 [==============================] - 0s 61ms/step - loss: 1.3332 - accuracy: 0.5225 - val_loss: 1.4026 - val_accuracy: 0.6250
Epoch 519/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.3534 - accuracy: 0.5045 - val_loss: 1.4008 - val_accuracy: 0.6250
Epoch 520/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.2616 - accuracy: 0.5225 - val_loss: 1.3964 - val_accuracy: 0.6250
Epoch 521/1000
1/1 [==============================] - 0s 48ms/step - loss: 1.2615 - accuracy: 0.5766 - val_loss: 1.3955 - val_accuracy: 0.6250
Epoch 522/1000

1/1 [==============================] - 0s 56ms/step - loss: 1.2285 - accuracy: 0.5676 - val_loss: 1.3187 - val_accuracy: 0.6250
Epoch 573/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.2626 - accuracy: 0.5405 - val_loss: 1.3156 - val_accuracy: 0.6250
Epoch 574/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.1744 - accuracy: 0.5586 - val_loss: 1.3143 - val_accuracy: 0.6250
Epoch 575/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.2325 - accuracy: 0.5405 - val_loss: 1.3144 - val_accuracy: 0.6250
Epoch 576/1000
1/1 [==============================] - 0s 64ms/step - loss: 1.2681 - accuracy: 0.5405 - val_loss: 1.3205 - val_accuracy: 0.6250
Epoch 577/1000
1/1 [==============================] - 0s 72ms/step - loss: 1.1764 - accuracy: 0.5495 - val_loss: 1.3159 - val_accuracy: 0.6250
Epoch 578/1000
1/1 [==============================] - 0s 68ms/step - loss: 1.2059 - accuracy: 0.5946 - val_loss: 1.3135 - val_accuracy: 0.6250
Epoch 579/1000

1/1 [==============================] - 0s 67ms/step - loss: 1.1476 - accuracy: 0.5495 - val_loss: 1.2335 - val_accuracy: 0.6667
Epoch 630/1000
1/1 [==============================] - 0s 55ms/step - loss: 1.1425 - accuracy: 0.5766 - val_loss: 1.2315 - val_accuracy: 0.6667
Epoch 631/1000
1/1 [==============================] - 0s 54ms/step - loss: 1.1416 - accuracy: 0.5586 - val_loss: 1.2294 - val_accuracy: 0.6667
Epoch 632/1000
1/1 [==============================] - 0s 54ms/step - loss: 1.1286 - accuracy: 0.5676 - val_loss: 1.2245 - val_accuracy: 0.6667
Epoch 633/1000
1/1 [==============================] - 0s 52ms/step - loss: 1.1268 - accuracy: 0.6126 - val_loss: 1.2232 - val_accuracy: 0.6667
Epoch 634/1000
1/1 [==============================] - 0s 55ms/step - loss: 1.1051 - accuracy: 0.5856 - val_loss: 1.2240 - val_accuracy: 0.6667
Epoch 635/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.1319 - accuracy: 0.5495 - val_loss: 1.2200 - val_accuracy: 0.6667
Epoch 636/1000

1/1 [==============================] - 0s 69ms/step - loss: 1.0935 - accuracy: 0.5946 - val_loss: 1.1449 - val_accuracy: 0.6667
Epoch 687/1000
1/1 [==============================] - 0s 56ms/step - loss: 1.0327 - accuracy: 0.5856 - val_loss: 1.1437 - val_accuracy: 0.6667
Epoch 688/1000
1/1 [==============================] - 0s 62ms/step - loss: 1.0515 - accuracy: 0.6396 - val_loss: 1.1453 - val_accuracy: 0.6667
Epoch 689/1000
1/1 [==============================] - 0s 60ms/step - loss: 1.0411 - accuracy: 0.5856 - val_loss: 1.1449 - val_accuracy: 0.6667
Epoch 690/1000
1/1 [==============================] - 0s 59ms/step - loss: 1.0880 - accuracy: 0.5946 - val_loss: 1.1423 - val_accuracy: 0.6667
Epoch 691/1000
1/1 [==============================] - 0s 60ms/step - loss: 1.0695 - accuracy: 0.5856 - val_loss: 1.1420 - val_accuracy: 0.6667
Epoch 692/1000
1/1 [==============================] - 0s 54ms/step - loss: 1.0209 - accuracy: 0.6396 - val_loss: 1.1409 - val_accuracy: 0.6667
Epoch 693/1000

1/1 [==============================] - 0s 59ms/step - loss: 0.9287 - accuracy: 0.6216 - val_loss: 1.0876 - val_accuracy: 0.6667
Epoch 744/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.9761 - accuracy: 0.6396 - val_loss: 1.0894 - val_accuracy: 0.6667
Epoch 745/1000
1/1 [==============================] - 0s 58ms/step - loss: 0.9726 - accuracy: 0.6306 - val_loss: 1.0875 - val_accuracy: 0.6667
Epoch 746/1000
1/1 [==============================] - 0s 59ms/step - loss: 1.0078 - accuracy: 0.5856 - val_loss: 1.0879 - val_accuracy: 0.6667
Epoch 747/1000
1/1 [==============================] - 0s 55ms/step - loss: 0.9923 - accuracy: 0.6216 - val_loss: 1.0888 - val_accuracy: 0.6667
Epoch 748/1000
1/1 [==============================] - 0s 64ms/step - loss: 0.9692 - accuracy: 0.6216 - val_loss: 1.0853 - val_accuracy: 0.6667
Epoch 749/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.9491 - accuracy: 0.6396 - val_loss: 1.0843 - val_accuracy: 0.6667
Epoch 750/1000

1/1 [==============================] - 0s 56ms/step - loss: 0.9452 - accuracy: 0.6306 - val_loss: 1.0728 - val_accuracy: 0.6667
Epoch 801/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.9258 - accuracy: 0.6667 - val_loss: 1.0708 - val_accuracy: 0.6667
Epoch 802/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.8674 - accuracy: 0.6577 - val_loss: 1.0673 - val_accuracy: 0.6667
Epoch 803/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.9309 - accuracy: 0.6216 - val_loss: 1.0656 - val_accuracy: 0.6667
Epoch 804/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.9341 - accuracy: 0.6486 - val_loss: 1.0672 - val_accuracy: 0.6667
Epoch 805/1000
1/1 [==============================] - 0s 92ms/step - loss: 0.8830 - accuracy: 0.6306 - val_loss: 1.0631 - val_accuracy: 0.6667
Epoch 806/1000
1/1 [==============================] - 0s 84ms/step - loss: 0.8683 - accuracy: 0.6577 - val_loss: 1.0635 - val_accuracy: 0.6667
Epoch 807/1000

1/1 [==============================] - 0s 56ms/step - loss: 0.8782 - accuracy: 0.6847 - val_loss: 1.0569 - val_accuracy: 0.6667
Epoch 858/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.8276 - accuracy: 0.6847 - val_loss: 1.0541 - val_accuracy: 0.6875
Epoch 859/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.8173 - accuracy: 0.6847 - val_loss: 1.0524 - val_accuracy: 0.6875
Epoch 860/1000
1/1 [==============================] - 0s 51ms/step - loss: 0.8482 - accuracy: 0.6937 - val_loss: 1.0525 - val_accuracy: 0.6875
Epoch 861/1000
1/1 [==============================] - 0s 52ms/step - loss: 0.8050 - accuracy: 0.6847 - val_loss: 1.0514 - val_accuracy: 0.6875
Epoch 862/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.8179 - accuracy: 0.6757 - val_loss: 1.0537 - val_accuracy: 0.6667
Epoch 863/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.8490 - accuracy: 0.6486 - val_loss: 1.0487 - val_accuracy: 0.6875
Epoch 864/1000

1/1 [==============================] - 0s 60ms/step - loss: 0.8170 - accuracy: 0.6847 - val_loss: 1.0533 - val_accuracy: 0.6875
Epoch 915/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.8336 - accuracy: 0.6937 - val_loss: 1.0543 - val_accuracy: 0.6875
Epoch 916/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.7945 - accuracy: 0.7027 - val_loss: 1.0533 - val_accuracy: 0.6875
Epoch 917/1000
1/1 [==============================] - 0s 49ms/step - loss: 0.8198 - accuracy: 0.6486 - val_loss: 1.0503 - val_accuracy: 0.6875
Epoch 918/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.8071 - accuracy: 0.6667 - val_loss: 1.0499 - val_accuracy: 0.6875
Epoch 919/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.8018 - accuracy: 0.6757 - val_loss: 1.0474 - val_accuracy: 0.6875
Epoch 920/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.8053 - accuracy: 0.6937 - val_loss: 1.0457 - val_accuracy: 0.6875
Epoch 921/1000

1/1 [==============================] - 0s 50ms/step - loss: 0.7956 - accuracy: 0.6847 - val_loss: 1.0486 - val_accuracy: 0.6875
Epoch 972/1000
1/1 [==============================] - 0s 48ms/step - loss: 0.7645 - accuracy: 0.7027 - val_loss: 1.0487 - val_accuracy: 0.6875
Epoch 973/1000
1/1 [==============================] - 0s 53ms/step - loss: 0.7883 - accuracy: 0.6667 - val_loss: 1.0525 - val_accuracy: 0.6875
Epoch 974/1000
1/1 [==============================] - 0s 53ms/step - loss: 0.7603 - accuracy: 0.7117 - val_loss: 1.0554 - val_accuracy: 0.6875
Epoch 975/1000
1/1 [==============================] - 0s 50ms/step - loss: 0.7557 - accuracy: 0.6847 - val_loss: 1.0526 - val_accuracy: 0.6875
Epoch 976/1000
1/1 [==============================] - 0s 56ms/step - loss: 0.7624 - accuracy: 0.6847 - val_loss: 1.0483 - val_accuracy: 0.6875
Epoch 977/1000
1/1 [==============================] - 0s 77ms/step - loss: 0.7367 - accuracy: 0.7207 - val_loss: 1.0497 - val_accuracy: 0.6875
Epoch 978/1000

In [57]:
yp = categorical.predict(sc.transform([[120,17.5,19,21.3,8.3922,2.9181]]))

In [58]:
yp

array([[4.5478475e-01, 5.3951520e-01, 1.3590802e-03, 3.5419371e-03,
        1.1756261e-05, 7.8390919e-08, 7.8717445e-04]], dtype=float32)

In [59]:
yp>0.5

array([[False,  True, False, False, False, False, False]])

In [63]:
yp = categorical.predict(sc.transform([[20,17.5,42.3,134.3,8.3922,0.9181]]))

In [64]:
print(yp)

[[1.9469137e-05 4.2611554e-27 6.9615252e-23 9.9998057e-01 0.0000000e+00
  0.0000000e+00 6.3749824e-17]]


In [65]:
yp = np.argmax(yp)#[0,0,0,0,1,0] 

In [66]:
index = ["bearm","parkki","perch","pike","roach","smelt","whitefih"]

In [67]:
index[yp]

'pike'

In [68]:
prediction = index[yp]

In [69]:
prediction

'pike'